'use strict';
const width = 12;
const height = 24;
const area = width * height;
console.log('value of area:', area);
console.log('type of area:', typeof area);
const bill = 800;
const payment = 1000;
const change = payment - bill;
console.log('value of change:', change);
console.log('type of change:', typeof change);
const quizzes = 85;
const midterm = 80;
const final = 95;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('type of grade:', typeof grade);
const firstName = 'Michael John';
const lastName = 'Pulusan';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('type of fullName:', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
const headCount = 10;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('type of isSparta:', typeof isSparta);
let motto = fullName;
motto += 'is the GOAT';
console.log('value of motto:', motto);
console.log('type of motto:', typeof motto);
